
import Controllers.*;
import Models.*;
import java.util.*;
import java.awt.Color;
import javax.persistence.EntityManagerFactory;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mrkjse
 */
public class MainFrame extends javax.swing.JFrame { 
    
    ArrayList<EntityManagerFactory> emfactoryList = null;
    DefaultController defaultController = null;
    HotelController hotelController = null;
    RoomController roomController = null;
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        defaultController = new DefaultController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        btnHotels = new javax.swing.JButton();
        btnRooms = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnGuests = new javax.swing.JButton();
        btnMemberships = new javax.swing.JButton();
        btnBookings = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        labelInstruction = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        labelLogIn = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));

        menuPanel.setOpaque(false);

        btnHotels.setBackground(new java.awt.Color(255, 255, 255));
        btnHotels.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHotels.setForeground(new java.awt.Color(0, 51, 51));
        btnHotels.setText("HOTELS");
        btnHotels.setBorderPainted(false);
        btnHotels.setOpaque(false);
        btnHotels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHotelsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHotelsMouseExited(evt);
            }
        });
        btnHotels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelsActionPerformed(evt);
            }
        });

        btnRooms.setBackground(new java.awt.Color(255, 255, 255));
        btnRooms.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRooms.setForeground(new java.awt.Color(0, 51, 51));
        btnRooms.setText("ROOMS");
        btnRooms.setBorderPainted(false);
        btnRooms.setOpaque(false);
        btnRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRoomsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRoomsMouseExited(evt);
            }
        });
        btnRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomsActionPerformed(evt);
            }
        });

        btnCustomers.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(0, 51, 51));
        btnCustomers.setText("CUSTOMERS");
        btnCustomers.setBorderPainted(false);
        btnCustomers.setOpaque(false);
        btnCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomersMouseExited(evt);
            }
        });

        btnGuests.setBackground(new java.awt.Color(255, 255, 255));
        btnGuests.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuests.setForeground(new java.awt.Color(0, 51, 51));
        btnGuests.setText("GUESTS");
        btnGuests.setBorderPainted(false);
        btnGuests.setOpaque(false);
        btnGuests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuestsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuestsMouseExited(evt);
            }
        });
        btnGuests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestsActionPerformed(evt);
            }
        });

        btnMemberships.setBackground(new java.awt.Color(255, 255, 255));
        btnMemberships.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMemberships.setForeground(new java.awt.Color(0, 51, 51));
        btnMemberships.setText("MEMBERSHIPS");
        btnMemberships.setBorderPainted(false);
        btnMemberships.setOpaque(false);
        btnMemberships.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMembershipsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMembershipsMouseExited(evt);
            }
        });

        btnBookings.setBackground(new java.awt.Color(255, 255, 255));
        btnBookings.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBookings.setForeground(new java.awt.Color(0, 51, 51));
        btnBookings.setText("BOOKINGS");
        btnBookings.setBorderPainted(false);
        btnBookings.setOpaque(false);
        btnBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingsMouseExited(evt);
            }
        });

        btnPayments.setBackground(new java.awt.Color(255, 255, 255));
        btnPayments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPayments.setForeground(new java.awt.Color(0, 51, 51));
        btnPayments.setText("PAYMENTS");
        btnPayments.setBorderPainted(false);
        btnPayments.setOpaque(false);
        btnPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentsMouseExited(evt);
            }
        });
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });

        labelInstruction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelInstruction.setText("Please select from the menu below.");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(btnGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHotels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMemberships)
                            .addComponent(btnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(222, 222, 222))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(labelInstruction)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(labelInstruction)
                .addGap(26, 26, 26)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHotels, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMemberships, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        labelLogIn.setText("You are not logged in.");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HOTEL MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogIn)
                                .addGap(34, 34, 34)
                                .addComponent(labelLogIn)
                                .addGap(32, 32, 32)
                                .addComponent(btnClose)))
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogIn)
                            .addComponent(labelLogIn)
                            .addComponent(btnClose)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnHotelsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHotelsMouseEntered
        // TODO add your handling code here:
        btnHotels.setBackground(Color.GRAY);
                
    }//GEN-LAST:event_btnHotelsMouseEntered

    private void btnHotelsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHotelsMouseExited
        // TODO add your handling code here:
        btnHotels.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnHotelsMouseExited

    private void btnRoomsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoomsMouseEntered
        // TODO add your handling code here:
        btnRooms.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnRoomsMouseEntered

    private void btnRoomsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoomsMouseExited
        // TODO add your handling code here:
        btnRooms.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnRoomsMouseExited

    private void btnCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseEntered
        // TODO add your handling code here:
        btnCustomers.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnCustomersMouseEntered

    private void btnCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseExited
        // TODO add your handling code here:
        btnCustomers.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCustomersMouseExited

    private void btnGuestsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuestsMouseEntered
        // TODO add your handling code here:
        btnGuests.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnGuestsMouseEntered

    private void btnGuestsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuestsMouseExited
        // TODO add your handling code here:
        btnGuests.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnGuestsMouseExited

    private void btnPaymentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentsMouseEntered
        // TODO add your handling code here:
        btnPayments.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnPaymentsMouseEntered

    private void btnPaymentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentsMouseExited
        // TODO add your handling code here:
        btnPayments.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnPaymentsMouseExited

    private void btnMembershipsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMembershipsMouseEntered
        // TODO add your handling code here:
        btnMemberships.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnMembershipsMouseEntered

    private void btnMembershipsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMembershipsMouseExited
        // TODO add your handling code here:
        btnMemberships.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnMembershipsMouseExited

    private void btnBookingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingsMouseEntered
        // TODO add your handling code here:
        btnBookings.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnBookingsMouseEntered

    private void btnBookingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingsMouseExited
        btnBookings.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnBookingsMouseExited

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        emfactoryList = defaultController.LogIn();
        
        boolean loggedIn = true;
        
        for (EntityManagerFactory emf : emfactoryList)
        {
            if (!emf.isOpen())
            {
                System.out.println(emf.getProperties());
                loggedIn = false;
            }
        }
        
        if (loggedIn)
        {
            labelLogIn.setText("You are now logged in.");
        }
        
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        for (EntityManagerFactory emf : emfactoryList)
        {
            emf.close();
        }
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnHotelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelsActionPerformed
        // TODO add your handling code here:
        if (emfactoryList != null)
        {
            hotelController = new HotelController(emfactoryList.get(0));
            //hotelController.getHotels();
            
            Hotel hotel = new Hotel();
            hotel.setHotelId(2);
            hotel.setAddress("101 Collins St. Melbourne VIC");
            hotel.setCity("Melbourne");
            hotel.setConstructionYear(new Date(2000,1,1));
            hotel.setContactNumber("+61474987964");
            hotel.setCountry("Australia");
            hotel.setEmailAddress("hello@loretta.com");
            hotel.setHotelName("Loretta Hotel");
            hotel.setHotelTypeCode(HotelTypeCode.FIVESTAR.code());
            
            hotelController.createHotel(hotel);
        }
    }//GEN-LAST:event_btnHotelsActionPerformed

    private void btnGuestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestsActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnGuestsActionPerformed

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        // TODO add your handling code here:
        if (emfactoryList != null)
        {
            roomController = new RoomController(emfactoryList.get(1));
            
            List<Room> rooms = roomController.getRooms();
            
            for (Room r : rooms)
            {
                System.out.println("Room number: " + r.getRoomNumber() + " - " + r.getRoomDescription());
            }
            
        }
    }//GEN-LAST:event_btnRoomsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookings;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnGuests;
    private javax.swing.JButton btnHotels;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnMemberships;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnRooms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelInstruction;
    private javax.swing.JLabel labelLogIn;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
